"""
xnn_delayed_recall.py -- The delayed 1-bit recall task: the first task in
this line of investigation actually designed to make persistent ASNP state
load-bearing, rather than incidental (tic-tac-toe is Markovian; the current
board already contains everything needed, which is exactly why the
persistent-state ablation there came back a null result).

Trial structure:
  tick 0        : cue tick. One of two cue input neurons fires (the bit to
                  remember). Distractor neurons also fire random noise.
  ticks 1..D    : delay. Cue neurons are silent. Distractor neurons keep
                  firing random noise every tick -- this is deliberate: an
                  all-silent input is a literal fixed point of this
                  network's dynamics (see paper Section 4.4), so a silent
                  delay period would let a network "solve" the task by
                  passively doing nothing. Active distractors force it to
                  actually hold the cue against ongoing interference.
  tick D+1      : probe tick. A dedicated probe-trigger neuron fires. The
                  network must report the ORIGINAL cue on the output
                  neurons -- not anything about the probe or the distractors.

Two conditions sharing the identical architecture and training rule:
  - full memory   : ordinary persistent-state XNN (state carries across
                    every tick of the trial, exactly as in Section 5.3/6).
  - ablated memory: an otherwise-identical network whose HIDDEN neurons are
                    forcibly zeroed after every tick (input/output neurons
                    behave normally). This is the negative control: it
                    should fail at essentially any D > 0. If it doesn't,
                    the task is leaking the answer through some channel
                    other than genuine cross-tick memory, and that would
                    need to be caught before trusting a positive result
                    from the full-memory condition.

Training is direct supervised delta-rule learning at the probe-tick readout,
weighted by a decaying eligibility trace accumulated across the WHOLE trial
(cue, delay, and probe ticks) -- not just the final tick. This generalizes
xnn_model.XNN.train_actor (which only credits the current tick's flat fired
set, validated on tic-tac-toe's single-decision-per-move structure) and was
found to be *necessary*, not optional: crediting only the probe tick leaves
whatever hidden-layer dynamics would need to encode and maintain the cue
completely untrained, since nothing during the cue/delay ticks ever receives
a training signal. This is not multi-step RL like tic-tac-toe -- it's a
single well-defined correct answer per trial, generated by the environment
itself rather than any external label, just with credit distributed back
across the ticks that led to it.
"""
from __future__ import annotations

from typing import List, Tuple

import numpy as np

from xnn_model import XNN, XNNConfig

N_DISTRACTOR = 6
N_INPUT = 2 + N_DISTRACTOR + 1     # 2 cue + distractors + 1 probe-trigger
N_OUTPUT = 2
CUE_IDX = [0, 1]
DISTRACTOR_IDX = list(range(2, 2 + N_DISTRACTOR))
PROBE_IDX = 2 + N_DISTRACTOR


def make_config(n_hidden: int, steps_per_tick: int = 2) -> XNNConfig:
    return XNNConfig(n_input=N_INPUT, n_hidden=n_hidden, n_output=N_OUTPUT,
                      n_value=4, steps_per_decision=steps_per_tick,
                      target_activity=0.25, homeostatic_lr=0.002, activity_ema_alpha=0.02)


def build_input(tick_type: str, cue: int, rng: np.random.Generator, context: str = 'A') -> np.ndarray:
    """tick_type in {'cue', 'delay', 'probe'}. context in {'A', 'B'}: in context
    B, the cue and two of the distractor channels swap physical roles -- a
    genuine encoding-level context change (which inputs matter changes),
    not just a harder version of the same problem. Whichever channels serve
    as the cue in the active context stay cleanly silent except during the
    cue tick, symmetric with the other context -- the noise-bearing channel
    set excludes them, so this isn't just a noisier version of the task."""
    vec = np.zeros(N_INPUT)

    if context == 'A':
        cue_channels = CUE_IDX
        noise_channels = DISTRACTOR_IDX
    else:
        cue_channels = [DISTRACTOR_IDX[0], DISTRACTOR_IDX[1]]
        noise_channels = CUE_IDX + DISTRACTOR_IDX[2:]

    vec[noise_channels] = (rng.random(len(noise_channels)) < 0.5).astype(float)

    if tick_type == 'cue':
        vec[cue_channels[cue]] = 1.0
    elif tick_type == 'probe':
        vec[PROBE_IDX] = 1.0
    return vec


def train_actor_traced(net: XNN, trace: np.ndarray, col_idx: int, signal: float,
                        c_w: float = 0.1, c_b: float = 0.1) -> None:
    """Like XNN.train_actor, but weighted by a continuous eligibility trace
    instead of a flat boolean fired_log -- every neuron's contribution is
    scaled by how recently (and how strongly) it fired, rather than getting
    the same full-strength update just for having fired at some point during
    the trial. This stays more selective as trial length grows, unlike the
    flat whole-trial fired-log approach, which becomes non-discriminating
    once nearly every neuron has fired at least once (a real risk here,
    since distractor neurons keep exciting the hidden layer throughout the
    whole delay period)."""
    net.W[:, col_idx] += signal * c_w * trace
    net.W[:, col_idx] = np.clip(net.W[:, col_idx], -1.0, 1.0)
    net.bias[col_idx] += signal * c_b
    net.bias[col_idx] = np.clip(net.bias[col_idx], 0.0, 1.0)


def run_trial(net: XNN, D: int, rng: np.random.Generator, train: bool,
              steps_per_tick: int, ablate_memory: bool,
              c_w: float = 0.1, c_b: float = 0.1, trace_decay: float = 0.7) -> Tuple[bool, int]:
    """Runs one full trial. Returns (correct, cue)."""
    cfg = net.config
    cue = int(rng.integers(2))
    state = net.new_state()
    trace = np.zeros(cfg.n_total)

    # cue tick
    input_vec = build_input('cue', cue, rng)
    state, fired = net.tick(state, input_vec, steps_per_tick, track=True)
    trace = trace * trace_decay
    trace[fired] = 1.0
    if ablate_memory:
        state[cfg.hidden_idx] = 0.0
        state[cfg.output_idx] = 0.0

    # delay ticks
    for _ in range(D):
        state[cfg.input_idx] = 0.0   # pre-clear: tick()'s clamp only overwrites input
                                      # AFTER each sub-step, so a stale value from the
                                      # previous tick would otherwise leak through the
                                      # first sub-step's dynamics before being overwritten
        input_vec = build_input('delay', cue, rng)
        state, fired = net.tick(state, input_vec, steps_per_tick, track=True)
        trace = trace * trace_decay
        trace[fired] = 1.0
        if ablate_memory:
            state[cfg.hidden_idx] = 0.0
            state[cfg.output_idx] = 0.0

    # probe tick
    state[cfg.input_idx] = 0.0
    input_vec = build_input('probe', cue, rng)
    state, fired = net.tick(state, input_vec, steps_per_tick, track=True)
    trace = trace * trace_decay
    trace[fired] = 1.0

    out_states = state[cfg.output_idx].copy()
    state[cfg.output_idx] = 0.0   # Clearing, as elsewhere

    predicted = int(np.argmax(out_states))
    correct = (predicted == cue)

    if train:
        target = np.zeros(N_OUTPUT)
        target[cue] = 1.0
        for i, global_idx in enumerate(cfg.output_idx):
            error = target[i] - out_states[i]
            train_actor_traced(net, trace, global_idx, error, c_w=c_w, c_b=c_b)

    return correct, cue


def train_and_eval(D: int, n_hidden: int, ablate_memory: bool, train_trials: int = 4000,
                    eval_trials: int = 400, steps_per_tick: int = 2, seed: int = 0,
                    c_w: float = 0.1, c_b: float = 0.1, trace_decay: float = 0.7) -> Tuple[XNN, float]:
    cfg = make_config(n_hidden, steps_per_tick)
    net = XNN(cfg, seed=seed)
    rng = np.random.default_rng(seed + 1000)

    for _ in range(train_trials):
        run_trial(net, D, rng, train=True, steps_per_tick=steps_per_tick,
                  ablate_memory=ablate_memory, c_w=c_w, c_b=c_b, trace_decay=trace_decay)

    eval_rng = np.random.default_rng(seed + 999999)
    correct_count = 0
    for _ in range(eval_trials):
        correct, _ = run_trial(net, D, eval_rng, train=False, steps_per_tick=steps_per_tick,
                                ablate_memory=ablate_memory, trace_decay=trace_decay)
        correct_count += correct

    return net, correct_count / eval_trials
